spring.application.name=NearBuzz

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nearbuzz}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=25
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=10000
spring.datasource.hikari.data-source-properties.stringtype=unspecified
spring.datasource.tomcat.connection-properties=stringtype=unspecified

spring.servlet.multipart.max-file-size=350MB
spring.servlet.multipart.max-request-size=1200MB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.jdbc.batch_size=5000
